#!/bin/bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
PROJECT_ROOT=${PROJECT_ROOT:-"$(cd "${SCRIPT_DIR}/../.." && pwd)"}

OUTPUT_DIR=${OUTPUT_DIR:-"${PROJECT_ROOT}/outputs/stage1_geobridge_fcp_feature_knn"}
LOG_DIR=${LOG_DIR:-"${PROJECT_ROOT}/logs/stage1_geobridge_fcp_feature_knn"}
INIT_CHECKPOINT_PATH=${INIT_CHECKPOINT_PATH:-"${PROJECT_ROOT}/outputs/stage1_continuity_v2_corrgraph_feature_knn/best.pt"}
FEATURE_LAYERS=${FEATURE_LAYERS:-"g11,g17,g23"}

USE_CONTINUITY_SELECTOR=${USE_CONTINUITY_SELECTOR:-"True"}
USE_ACTIVATED_CORR_GRAPH=${USE_ACTIVATED_CORR_GRAPH:-"True"}
GEOMETRY_CACHE_REQUIRED=${GEOMETRY_CACHE_REQUIRED:-"True"}
ONLINE_FALLBACK=${ONLINE_FALLBACK:-"False"}
FREEZE_GEO_PROJECTOR=${FREEZE_GEO_PROJECTOR:-"True"}

# SpatialFit Stage 1 final defaults: keep MGC + contrastive + selector as the main story.
CORR_NCE_WEIGHT=${CORR_NCE_WEIGHT:-0.30}
ATTN_WEIGHT=${ATTN_WEIGHT:-0.00}
LOV_GLOBAL_WEIGHT=${LOV_GLOBAL_WEIGHT:-0.00}
VAR_WEIGHT=${VAR_WEIGHT:-0.01}
CUS_LOSS_WEIGHT=${CUS_LOSS_WEIGHT:-0.20}
CUS_BUDGET_RATIO=${CUS_BUDGET_RATIO:-0.20}
CUS_BUDGET_WEIGHT=${CUS_BUDGET_WEIGHT:-0.10}
CUS_TARGET_TEMPERATURE=${CUS_TARGET_TEMPERATURE:-0.10}

MAX_STEPS=${MAX_STEPS:-20000}
SAVE_STEPS=${SAVE_STEPS:-1000}
LOGGING_STEPS=${LOGGING_STEPS:-50}

export OUTPUT_DIR LOG_DIR INIT_CHECKPOINT_PATH
export FEATURE_LAYERS
export USE_CONTINUITY_SELECTOR USE_ACTIVATED_CORR_GRAPH
export GEOMETRY_CACHE_REQUIRED ONLINE_FALLBACK FREEZE_GEO_PROJECTOR
export CORR_NCE_WEIGHT ATTN_WEIGHT LOV_GLOBAL_WEIGHT VAR_WEIGHT
export CUS_LOSS_WEIGHT CUS_BUDGET_RATIO CUS_BUDGET_WEIGHT CUS_TARGET_TEMPERATURE
export MAX_STEPS SAVE_STEPS LOGGING_STEPS

exec bash "${SCRIPT_DIR}/train_stage1_continuity_v2.sh"
